os:
- linux
- windows
addons:
  artifacts:
    paths:
    - artifacts
env:
  global:
  - QT_VERSION=5.12.9
language: cpp
services:
- docker
archlinux:
  packages:
  - python
  - boost
  - qt5
  - gst-plugins-bad
  - gst-plugins-bad-libs
  - gst-plugins-base
  - gst-plugins-base-libs
  - gst-plugins-good
  - gst-plugins-ugly
  - cmake
  - squashfuse
  mount:
  - "~/.pkg-cache:/var/cache/pacman/pkg"
  script:
  - git submodule init && git submodule update
  - cmake . -B out
  - VERBOSE=1 cmake --build out --config Release -j2
  - "./AppImageBuild/linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir
    AppDir --output appimage --create-desktop-file -e out/bin/MusicQuizGUI -i icons/MusicQuizGUI.png"
  - "./AppImageBuild/linuxdeploy-plugin-qt-x86_64.AppImage --appdir AppDir"
  - "./AppImageBuild/linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage"
  - mv MusicQuizGUI*.AppImage artifacts/MusicQuizGUI.AppImage
script:
- mkdir artifacts
- if [ "$TRAVIS_OS_NAME" = "linux" ];   then curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh
  | bash; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then git submodule init && git submodule update;
  fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then curl -LO https://code.qt.io/cgit/qbs/qbs.git/plain/scripts/install-qt.sh;
  fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./install-qt.sh   --version ${QT_VERSION}
  --toolchain win64_msvc2017_64 qtbase qtsvg qtmultimedia qttools; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install boost-msvc-14.1; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then export "PATH=/c/Qt/${QT_VERSION}/msvc2017_64:/c/Qt/5.12.9/msvc2017_64/bin:$PATH";
  fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake . -G "Visual Studio 15 2017 Win64"
  -B out; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then VERBOSE=1 cmake --build out --config
  Release -j2; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then curl -LO https://github.com/SerGreen/Appacker/releases/download/v1.3.6/Appacker.exe;
  fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then chmod +x Appacker.exe; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then mkdir MusicQuizPackage; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cp out/bin/Release/MusicQuizGUI.exe MusicQuizPackage/MusicQuizGUI.exe;
  fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cp -r installation/dlls/* MusicQuizPackage/;
  fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./Appacker.exe -s MusicQuizPackage/ -e
  MusicQuizGUI.exe -d artifacts/MusicQuizGUI.exe || true; fi
before_deploy:
- git config --local user.name "StefanRvO"
- git config --local user.email "stefan@stefanrvo.dk"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: jWh6M7GjPTCHygwVUAr2WTgV9AuJclZYZYvMMmGqpAUhi1U0FfB6PmRf2MeHjfPRRtvN/6YhCsRXhZ2KoZGGnVLtip4VyM+/B2AOcBmK0hlnIbFEyr7Ef/4CKjmyQxTfClqAx+lJdKJjyiGriJNZp34g3YR8tvwj8VM5au/V57vFpfFaLVgPiCepVqDvbQ5HRXN2DRs2Ci9zgDdCkKRq4uzWDo9A9YNxywz30Ixp65/WT9TKbf0pkfCISi053oo0tLeDZet96dIFfQUTOlxpkABhYyUwom1hLJM3xGtlCXa7ZwLa/hDEZP/K3h8R8vp3ytO4X66CKNmXLw9yHJw0/u32guQ0DezTjMUJMqsxldI8d3Q+uHZCx6ly4NG3s0WI/9Ak7uUaJG+p1mek2SsCFhQhF5IqgMRf/oXiOpou7qNISAAm56lIKMwS5sqvYgF9ZKaE1aZWhPnDn5SrjwMbXvRctgzOj9s3TySrI2Mst9gnNolUMmMkAQzZtQwkLVGIlVfBfInpslIu/gdAvLKlUAZjHq7wjIJxV1F5cioCPMuHHEJl/EgEn2iWiwgyE0Oj1S4ZNeI+TkSU2TVAF3PhkIG9t3PeX/ONDm5yUK8oSNNGGoUGee0BfXfcw3rmT6VQCMQ+MwnszU1zn+veKdpm0IdWxiltIpCmcPIIbmFY+Ak=
  file: 
    - "artifacts/MusicQuizGUI.exe"
    - "artifacts/MusicQuizGUI.AppImage"
  skip_cleanup: 'true'
