name: CMake build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:        
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
        - os: ubuntu
          env: CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9
          releasefile: MusicQuizGUI.AppImage
        - os: windows
          releasefile: MusicQuizGUI.exe



    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Submodules
      run: git submodule init && git submodule update
    - name: cmake
      run: ${{ matrix.env }} cmake . ${{ matrix.cmake_params }} -DBoost_ARCHITECTURE=-x64 -DBOOST_ROOT=$BOOST_ROOT_1_72_0  -B out
    - name: build
      run: VERBOSE=1 cmake --build out --config Release -j2
    - name: package
      run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
            curl -L https://github.com/SerGreen/Appacker/releases/download/v1.3.6/Appacker.exe --output Appacker.exe
            mkdir MusicQuizPackage
            cp out/bin/Release/MusicQuizGUI.exe MusicQuizPackage/MusicQuizGUI.exe
            cp -r installation/dlls/* MusicQuizPackage/
            ./Appacker.exe -s MusicQuizPackage/ -e MusicQuizGUI.exe -d ${{ matrix.releasefile }} || true
            sleep 10
           else
            curl -L https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage --output linuxdeploy-x86_64.AppImage
            chmod +x linuxdeploy-x86_64.AppImage
            curl -L https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage --output linuxdeploy-plugin-qt-x86_64.AppImage
            chmod +x linuxdeploy-plugin-qt-x86_64.AppImage
            sudo apt-get install -y libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
            ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir AppDir --output appimage --create-desktop-file -e out/bin/MusicQuizGUI -i icons/MusicQuizGUI.png --plugin qt
            mv MusicQuizGUI*.AppImage ${{ matrix.releasefile }}
           fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.releasefile }}
        path: ${{ matrix.releasefile }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.releasefile }}
        asset_name: ${{ matrix.releasefile }}
        tag: ${{ github.run_number }}
